Translate Ruby 2.4.0 (es)
ruby/www.ruby-lang.org pull request #1547
Opened 2017-01-04 15:39 UTC by FerPerales

2017-01-04 15:41 UTC, stomar commented
cc @dabit

2017-01-04 15:43 UTC, stomar commented on es/news/_posts/2016-12-25-ruby-2-4-0-released.md
> +lang: en
es

2017-01-09 20:19 UTC, gfvcastro requested changes
Thank you for your contribution!

2017-02-12 16:29 UTC, stomar commented on es/news/_posts/2016-12-25-ruby-2-4-0-released.md
> +title: "Liberado Ruby 2.4.0"
However, "Liberado Ruby ..." has previously been used **very** often, too. And it has the "full name" of the version (i.e. "Ruby 2.4.0") in unmodified form.

But you must decide what sounds better in `es`.

2017-02-12 16:33 UTC, stomar commented
And, please wrap lines at max. 80 characters, where possible.

2017-06-01 00:03 UTC, FerPerales commented
@gfvcastro changes done. Sorry for letting this stale for so long

2017-06-03 09:08 UTC, stomar commented
This can not be merged. **Never** merge upstream into your feature branch.
(See also https://github.com/ruby/www.ruby-lang.org/wiki#commits-and-commit-messages.)

Please rebase your feature branch onto current master or drop the merge commit and repush, or open a clean PR.

2017-06-03 09:08 UTC, closed without merging