Fix /en/documentation/faq/2/index.md
ruby/www.ruby-lang.org pull request #2852
Opened 2022-05-24 14:36 UTC by Abhideveloper28

This statement looks wrong to me, It said a `A `def` statement outside of
a class definition become private methods of class Object`
that is not correct. I can call method (that define outside any class) to object of class Object.

2022-10-30 22:37 UTC, stomar commented
The original statement seems to be correct:

~~~ ruby
irb(main):001:0> def my_test_method; end
=> :my_test_method
irb(main):002:0> Object.public_methods.grep /my/
=> []
irb(main):003:0> Object.private_methods.grep /my/
=> [:my_test_method]
~~~

2022-10-31 20:51 UTC, stomar requested changes
Please clarify your statement _"I can call method (that define outside any class) to object of class Object"_ and what you did exactly.

2024-04-05 22:24 UTC, jcsahnwaldt commented
I think this can be closed without merging. The PR is almost two years old, OP didn't respond to questions, and the current version of the text seems to be correct.

2026-09-15 02:28 UTC, hsbt commented
The FAQ statement is correct. A top-level `def` defines a private method on `Object`, as shown above.

2026-09-15 02:28 UTC, closed without merging