Translate CVE-2021-33621 HTTP response splitting in CGI news post (pt)
ruby/www.ruby-lang.org pull request #2974
Opened 2023-01-27 15:19 UTC by guicruzzs

Translation of the post about [HTTP response splitting in CGI](https://github.com/advisories/GHSA-vc47-6rqg-c7f5) to :brazil: :portugal:

Please, review this :pray:

2023-01-30 13:38 UTC, jcserracampos requested changes

2023-01-30 13:38 UTC, jcserracampos commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Nós lançamos gem cgi versão 0.3.5, 0.2.2, e 0.1.0.2 que possui uma correção de segurança para uma vulnerabilidade de HTTP response splitting.
```suggestion
Nós lançamos as versões da gem cgi 0.3.5, 0.2.2, e 0.1.0.2 que possuem uma correção de segurança para uma vulnerabilidade de HTTP response splitting.
```

2023-01-30 13:38 UTC, jcserracampos commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Essa vulnerabilidade foi atribuída ao identificador CVE [CVE-2021-33621](https://nvd.nist.gov/vuln/detail/CVE-2021-33621).
```suggestion
Essa vulnerabilidade foi atribuída ao identificador [CVE-2021-33621](https://nvd.nist.gov/vuln/detail/CVE-2021-33621).
```

2023-01-30 13:38 UTC, jcserracampos commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Se uma aplicação que gera respostas HTTP usando a gem cgi com uma input não confiável do usuário, um atacante pode explorá-la injetando um body e/ou header malicioso na resposta HTTP.
Eu acho que "com uma input" não ficou tão claro.
Talvez usar "com uma entrada de dados não confiável"?

2023-01-30 13:38 UTC, jcserracampos commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Também, os conteúdos de um objeto `CGI::Cookie` não eram verificado apropriadamente. Se uma aplicação cria um objeto `CGI::Cookie` baseado no input do usuário, um atacante pode explorá-lo para injeta
```suggestion
Também, os conteúdos de um objeto `CGI::Cookie` não eram verificadow apropriadamente. Se uma aplicação cria um objeto `CGI::Cookie` baseado no input do usuário, um atacante pode explorá-lo para injetar atributos inválidos no cabeçalho `Set-Cookie`. Nós achamos tais aplicações indesejadas, mas incluímos uma alteração para verificar os argumentos em `CGI::Cookie#initialize` preventivamente.
```

2023-01-30 13:38 UTC, jcserracampos commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Por favor atualize a gem cgi para a versão 0.3.5, 0.2.2, e 0.1.0.2, ou maiores. Você pode usar `gem update cgi` para atualizá-la.
```suggestion
Por favor atualize a gem cgi para as versões 0.3.5, 0.2.2, e 0.1.0.2, ou maiores. Você pode usar `gem update cgi` para atualizá-la.
```

2023-01-31 17:00 UTC, guicruzzs commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Se uma aplicação que gera respostas HTTP usando a gem cgi com uma input não confiável do usuário, um atacante pode explorá-la injetando um body e/ou header malicioso na resposta HTTP.
eu fiquei nessa dúvida também
acho que é uma ótima sugestão

2023-01-31 17:06 UTC, guicruzzs commented on pt/news/_posts/2022-11-22-http-response-splitting-in-cgi-cve-2021-33621.md
> +Também, os conteúdos de um objeto `CGI::Cookie` não eram verificado apropriadamente. Se uma aplicação cria um objeto `CGI::Cookie` baseado no input do usuário, um atacante pode explorá-lo para injeta
eu entendi o plural aqui :+1:

2023-04-05 02:32 UTC, hsbt approved these changes

2023-04-05 02:35 UTC, merged