Translations of Ruby 3-x release notes of March 30th 2023 (es)
ruby/www.ruby-lang.org pull request #3052
Opened 2023-04-28 13:51 UTC by vtamara

2023-05-03 19:11 UTC, gfvcastro requested changes
Thank you for your contribution!

2023-05-03 19:11 UTC, gfvcastro commented on es/news/_posts/2023-03-30-ruby-3-1-4-released.md
> +Ver detalles en la [publicación en GitHub](https://github.com/ruby/ruby/releases/tag/v3_1_4).
```suggestion
Se ha publicado Ruby 3.1.4.

Esta versión incluye correcciones de seguridad.
Por favor vea detalles en los siguientes temas.

* [CVE-2023-28755: Vulnerabilidad ReDoS en URI]({%link es/news/_posts/2023-03-28-redos-in-uri-cve-2023-28755.md %})
* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link es/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})

Ver más detalles en la [publicación en GitHub](https://github.com/ruby/ruby/releases/tag/v3_1_4).
```

2023-05-03 19:11 UTC, gfvcastro commented on es/news/_posts/2023-03-30-ruby-3-2-2-released.md
> +* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})
```suggestion
* [CVE-2023-28755: Vulnerabilidad ReDoS en URI]({%link es/news/_posts/2023-03-28-redos-in-uri-cve-2023-28755.md %})
* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link es/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})
```

2023-05-04 00:25 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-2-7-8-released.md
> +* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})
Yes. Done. Thank you.

2023-05-04 00:25 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-3-0-6-released.md
> +* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})
Yes. Done. Thank you.

2023-05-04 00:26 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-2-7-8-released.md
> +Después de esta versión, Ruby 2.7 llega a su EOL (Fin de vida).
Yes. Done. Thank you.

2023-05-04 00:26 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-3-0-6-released.md
> +o 3.2
Yes. Done. Thank you.

2023-05-04 00:27 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-3-1-4-released.md
> +Ver detalles en la [publicación en GitHub](https://github.com/ruby/ruby/releases/tag/v3_1_4).
The original post in english doesn't include that information, and according to the posts of the vulnerabilites Ruby 3.1.4 is not vulnerable (it is required just to update the gems uri and time).

2023-05-04 00:27 UTC, vtamara commented on es/news/_posts/2023-03-30-ruby-3-2-2-released.md
> +* [CVE-2023-28756: Vulnerabilidad ReDoS en Time]({%link en/news/_posts/2023-03-30-redos-in-time-cve-2023-28756.md %})
Yes. Done. Thank you.

2023-05-04 00:30 UTC, merged

2023-05-04 14:06 UTC, gfvcastro commented on es/news/_posts/2023-03-30-ruby-3-1-4-released.md
> +Ver detalles en la [publicación en GitHub](https://github.com/ruby/ruby/releases/tag/v3_1_4).
Hey @vtamara, from what I see, https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2023-03-30-ruby-3-1-4-released.md includes that information.