Translate Ruby 3.4.0 and 3.4.1 Released (zh_tw)
ruby/www.ruby-lang.org pull request #3450
Opened 2024-12-26 15:18 UTC by timfanda35

- Translate Ruby 3.4.0 Released (zh_tw)
- Translate Ruby 3.4.1 Released (zh_tw)

Thank you.

2024-12-30 17:45 UTC, bugtender requested changes
Thank you @timfanda35 that's lovely.
Just a little typo that needs to be fixed. 👍

Happy holiday! 🎄

2024-12-31 01:58 UTC, timfanda35 commented on zh_tw/news/_posts/2024-12-25-ruby-3-4-0-released.md
> +將 Prism 作為預設的解析氣，為 socket 函式庫加入 Happy Eyeballs Version 2 支援，改進 YJIT，加入 Modular GC，與其他更多.
I fixed it, thank you.

2024-12-31 22:59 UTC, bugtender approved these changes

2024-12-31 23:04 UTC, merged

2024-12-31 23:06 UTC, bugtender commented
Thank you and Happy new year! 🎉